name: ci
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: true
      matrix:
        nginx:
        - "1.26.3"
        flavor:
        - tsuru
        openresty_package_version:
        - 1.27.1.1-1~bookworm1
        experimental:
        - false

    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-qemu-action@v2
    - uses: docker/setup-buildx-action@v2
    - uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    - run: |
        echo MODULES=$(jq -er '.flavors[] | select(.name == "${{ matrix.flavor }}") | .modules | join(",")' flavors.json) >> $GITHUB_ENV
        echo LUA_MODULES=$(jq -er '.flavors[] | select(.name == "${{ matrix.flavor }}") | [ .lua_modules[]? ] | join(",")' flavors.json) >> $GITHUB_ENV
        if [[ "${{ github.ref }}" == "refs/heads/main" ]] || [[ "${{ github.ref }}" == refs/tags/* ]]; then
          echo DOCKER_TAGS=tsuru/nginx-${{ matrix.flavor }}:${{ matrix.nginx }},tsuru/nginx-${{ matrix.flavor }}:${{ matrix.nginx }}-${GITHUB_REF##*/} >> $GITHUB_ENV
        else
          echo DOCKER_TAGS=tsuru/nginx-${{ matrix.flavor }}:${{ matrix.nginx }}-${GITHUB_REF##*/} >> $GITHUB_ENV
        fi
    - uses: docker/build-push-action@v4
      with:
        load: true
        tags: ${{ env.DOCKER_TAGS }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
        build-args: |
          nginx_version=${{ matrix.nginx }}
          openresty_package_version=${{ matrix.openresty_package_version }}
          modules=${{ env.MODULES }}
          lua_modules=${{ env.LUA_MODULES }}
    - run: make test flavor=${{ matrix.flavor }} nginx_version=${{ matrix.nginx }}
    - uses: docker/login-action@v2
      if: github.event_name != 'pull_request'
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - uses: docker/build-push-action@v4
      if: github.event_name != 'pull_request'
      with:
        push: true
        tags: ${{ env.DOCKER_TAGS }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
        platforms: linux/amd64,linux/arm64
        build-args: |
          nginx_version=${{ matrix.nginx }}
          modules=${{ env.MODULES }}
          lua_modules=${{ env.LUA_MODULES }}